version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/projectDaria/jobScheduler
hooks:
  AfterInstall:
    - location: afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: afterUpdate.sh
      timeout: 300
      runas: root